# Generated by Django 5.0 on 2024-12-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_lists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Preço",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="purchased",
            field=models.BooleanField(default=False, verbose_name="Comprado"),
        ),
        migrations.AlterField(
            model_name="item",
            name="quantity",
            field=models.IntegerField(default=1, verbose_name="Quantidade"),
        ),
        migrations.AlterField(
            model_name="item",
            name="unit",
            field=models.CharField(blank=True, max_length=50, verbose_name="Unidade"),
        ),
    ]
