# Generated by Django 5.0 on 2024-12-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_lists", "0002_alter_item_name_alter_item_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="quantity",
            field=models.IntegerField(blank=True, null=True, verbose_name="Quantidade"),
        ),
    ]
