# Generated by Django 5.0 on 2025-12-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0003_alter_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Foto do Produto'),
        ),
    ]
